
const tableStatusCodes_enUS = {
    '100': "Continue",
    '101': "Switching Protocols",
    '102': "Processing",
    '200': "OK",
    '201': "Created",
    '202': "Accepted",
    '203': "Non-authoritative Information",
    '204': "No Content",
    '205': "Reset Content",
    '206': "Partial Content",
    '207': "Multi-Status",
    '208': "Already Reported",
    '226': "IM Used",
    '300': "Multiple Choices",
    '301': "Moved Permanently",
    '302': "Found",
    '303': "See Other",
    '304': "Not Modified",
    '305': "Use Proxy",
    '306': "Switch Proxy",
    '307': "Temporary Redirect",
    '308': "Permanent Redirect",
    '400': "Bad Request",
    '401': "Unauthorized",
    '402': "Payment Required",
    '403': "Forbidden",
    '404': "Not Found",
    '405': "Method Not Allowed",
    '406': "Not Acceptable",
    '407': "Proxy Authentication Required",
    '408': "Request Timeout",
    '409': "Conflict",
    '410': "Gone",
    '411': "Length Required",
    '412': "Precondition Failed",
    '413': "Payload Too Large",
    '414': "Request-URI Too Long",
    '415': "Unsupported Media Type",
    '416': "Requested Range Not Satisfiable",
    '417': "Expectation Failed",
    '418': "I'm a teapot",
    '421': "Misdirected Request",
    '422': "Unprocessable Entity",
    '423': "Locked",
    '424': "Failed Dependency",
    '426': "Upgrade Required",
    '428': "Precondition Required",
    '429': "Too Many Requests",
    '431': "Request Header Fields Too Large",
    '444': "Connection Closed Without Response",
    '451': "Unavailable For Legal Reasons",
    '499': "Client Closed Request",
    '500': "Internal Server Error",
    '501': "Not Implemented",
    '502': "Bad Gateway",
    '503': "Service Unavailable",
    '504': "Gateway Timeout",
    '505': "HTTP Version Not Supported",
    '506': "Variant Also Negotiates",
    '507': "Insufficient Storage",
    '508': "Loop Detected",
    '510': "Not Extended",
    '511': "Network Authentication Required",
    '599': "Network Connect Timeout Error"
}

const tableStatusCodes_ptBR = {
    '100': "Continuar",
    '101': "Mudando Protocolos",
    '102': "Processando",
    '200': "OK",
    '201': "Criado",
    '202': "Aceito",
    '203': "Information Não Autorizado",
    '204': "Nenhum Conteúdo",
    '205': "Resetar Conteúdo",
    '206': "Conteúdo Parcial",
    '300': "Múltipla Escolha",
    '301': "Movido Permanentemente",
    '302': "Encontrado",
    '303': "Veja Outro",
    '304': "Não Modificado",
    '305': "Use Proxy",
    '306': "Proxy Trocado",
    '400': "Solicitação Inválida",
    '401': "Não autorizado",
    '402': "Pagamento Necessário",
    '403': "Acesso Negado",
    '404': "Não Encontrado",
    '405': "Método Não Permitido",
    '406': "Não Aceito",
    '407': "Autenticação de Proxy Necessária",
    '408': "Tempo de Solicitação Esgotado",
    '409': "Conflito",
    '410': "Perdido",
    '411': "Duração Necessária",
    '412': "Falha de Pré-condição",
    '413': "Solicitação da Entidade Muito Extensa",
    '414': "Solicitação de URL Muito Longa",
    '415': "Tipo de Mídia Não Suportado",
    '416': "Solicitação de Faixa Não Satisfatória",
    '417': "Falha Na Expectativa",
    '500': "Erro Interno do Servidor",
    '501': "Não Implementado",
    '502': "Porta de Entrada Ruim",
    '503': "Serviço Indisponível",
    '504': "Tempo Limite da Porta de Entrada",
    '505': "Versão HTTP Não Suportada",
    '506': "Variante Também Negocia",
    '507': "Armazenamento Insuficiente",
    '508': "Loop Detectado",
    '510': "Não Estendido",
    '511': "Requer Autenticação de Rede",
    '599': "Erro de Tempo Limite de Conexão à Rede"
}

const tableStatusCodes_zhCN = {
    '100': "继续",
    '101': "切换协议",
    '102': "处理中",
    '200': "成功",
    '201': "已创建",
    '202': "已接受",
    '203': "非授权信息",
    '204': "无内容",
    '205': "重置内容",
    '206': "部分内容",
    '300': "多种选择",
    '301': "永久移动",
    '302': "临时移动",
    '303': "查看其他位置",
    '304': "未修改",
    '305': "使用代理",
    '306': "切换代理",
    '307': "临时重定向",
    '400': "错误请求",
    '401': "未授权",
    '402': "需要付款",
    '403': "禁止",
    '404': "未找到",
    '405': "方法禁用",
    '406': "不接受",
    '407': "需要代理授权",
    '408': "请求超时",
    '409': "冲突",
    '410': "已删除",
    '411': "需要有效长度",
    '412': "未满足前提条件",
    '413': "请求实体过大",
    '414': "请求的 URI 过长",
    '415': "不支持的媒体类型",
    '416': "请求范围不符合要求",
    '417': "未满足期望值",
    '500': "服务器内部错误",
    '501': "尚未实施",
    '502': "错误网关",
    '503': "服务不可用",
    '504': "网关超时",
    '505': "HTTP 版本不受支持",
    '506': "变体也可协商",
    '507': "存储空间不足",
    '508': "检测到循环",
    '510': "不扩展",
    '511': "需要网络验证",
    '599': "网络连接超时错误"
}

// TODO: add other languages
function getHttpStatusDescription(statusCode, lang) {
    lang = lang.toLowerCase()
    if (lang == 'pt-br')            // Portuguese - Brazil
        return tableStatusCodes_ptBR[statusCode]
    else if (lang == 'zh-cn')       // Chinese (Simplified)
        return tableStatusCodes_zhCN[statusCode]
    else
        return tableStatusCodes_enUS[statusCode]    // English by default
}

module.exports = {
    getHttpStatusDescription
}